### ISSUE TITLE
有前端代码嘛？

### ISSUE THREAD

**Issue by echoboss** [luxun9527/gex#1]

**Comment by ikun2021** [comment]
我对前端不太熟悉，前端代码主要是实现了功能。有很多不完善的地方。暂时不提供，可以通过swaager文件查看接口的定义和proto中ws推送数据的定义。

**Comment by zxxsong** [comment]
同求前端代码

**Comment by ikun2021** [comment]
最新有时间学了一下前端，这是我重构的前端ui，使用vue3+elementui  https://github.com/luxun9527/gex-ui 希望对你有帮助
