### ISSUE TITLE
请教一下，这三个文件是怎么编译出来的

### ISSUE THREAD

**Issue by wangzhensi** [luxun9527/gex#10]
- deploy/depend/dtm/dtm
- deploy/depend/ws/proxy/proxy
- deploy/depend/ws/socket/socket

**Comment by ikun2021** [comment]
deploy/depend/dtm/dtm 来自开源分布式框架
deploy/depend/ws/proxy/proxy 
deploy/depend/ws/socket/socket
是我另一个仓库gpush的代码，本周会维护一下代码
