### ISSUE TITLE
matchrpc error  GetOrderAllPendingOrder  

### ISSUE THREAD

**Issue by surfy1h** [luxun9527/gex#8]
Hey Thank you for this project I am really a big fan. 
I have all the docker containers working but matcher rpc i get the following error PANIC	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:21	call GetOrderAllPendingOrder failed rpc error: code = Unavailable desc = last resolver error: produced zero addresses

eCoinPrecValue:0 BaseCoinPrec:{_:[] v:0} QuoteCoinPrec:{_:[] v:0}}	{"project": "match-rpc", "caller": "svc/service_context.go:37"}
2024-06-23-07:22:22	ERROR	/root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/zrpc/resolver/internal/discovbuilder.go:34	bad resolver state	{"project": "match-rpc", "caller": "internal/discovbuilder.go:34"}
github.com/zeromicro/go-zero/zrpc/resolver/internal.(*discovBuilder).Build.func2
	/root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/zrpc/resolver/internal/discovbuilder.go:34
github.com/zeromicro/go-zero/zrpc/resolver/internal.(*discovBuilder).Build
	/root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/zrpc/resolver/internal/discovbuilder.go:38
google.golang.org/grpc.(*ccResolverWrapper).start.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.60.0/resolver_wrapper.go:80
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run
	/root/go/pkg/mod/google.golang.org/grpc@v1.60.0/internal/grpcsync/callback_serializer.go:82
2024-06-23-07:22:22	PANIC	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:21	call GetOrderAllPendingOrder failed rpc error: code = Unavailable desc = last resolver error: produced zero addresses
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/zeromicro/go-zero/core/logx.writeSevere({0xc00010cd00, 0x75})
	/root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/logx/logs.go:505 +0x34
github.com/zeromicro/go-zero/core/logx.Severef({0x23a411a?, 0x26ce3d8?}, {0xc000597bc8?, 0xc0006f3c20?, 0x0?})
	/root/go/pkg/mod/github.com/zeromicro/go-zero@v1.6.1/core/logx/logs.go:308 +0x2f
github.com/luxun9527/gex/app/match/rpc/internal/bootstrap.loadOrder(0xc0007905a0)
	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:21 +0xb7
github.com/luxun9527/gex/app/match/rpc/internal/bootstrap.Start(0xc0007905a0)
	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:15 +0x18
main.main()
	/root/gex/app/match/rpc/match.go:29 +0xc8
	{"project": "match-rpc"}
github.com/luxun9527/gex/app/match/rpc/internal/bootstrap.loadOrder
	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:21
github.com/luxun9527/gex/app/match/rpc/internal/bootstrap.Start
	/root/gex/app/match/rpc/internal/bootstrap/bootloader.go:15

**Comment by surfy1h** [comment]
Fixed it , rebuilt the MySQL Docker container

**Comment by ikun2021** [comment]
matchrpc  depend orderrpc，  load pending order from orderrpc ，it must watting orderrpc started

**Comment by surfy1h** [comment]
sorry do you have instructions for the  pending order or what service to start first ?
